services:
  nginx:
    image: nginx:1.28-alpine
    container_name: annuaire-nginx
    restart: unless-stopped
    ports:
      - "8889:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    depends_on:
      - annuaire-frontend
      - annuaire-backend
    networks:
      - annuaire_staging_net

  annuaire-frontend:
    image: ctrldaviddee/annuaire_did:staging-latest
    container_name: annuaire-frontend
    restart: unless-stopped
    env_file:
      - .env.frontend
    environment:
      - NODE_ENV=production
    expose:
      - "3000"
    networks:
      - annuaire_staging_net

  annuaire-backend:
    image: ctrldaviddee/annuaire_did_be:staging-latest
    container_name: annuaire-backend
    restart: unless-stopped
    env_file:
      - .env.backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    networks:
      - annuaire_staging_net

  db:
    image: postgres:18
    container_name: annuaire-db
    env_file:
      - .env.backend
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}", "-d annuaire_did"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    restart: unless-stopped
    networks:
      - annuaire_staging_net

  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: annuaire-rabbitmq
    volumes:
      - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env.backend
    ports:
      - "5672:5672"
      - "15672:15672"
    logging:
      driver: "json-file"
      options:
        max-size: "170m"
        max-file: "5"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
    networks:
      - annuaire_staging_net

  celery:
    image: ctrldaviddee/annuaire_did_be:staging-latest
    container_name: annuaire-celery
    #command: celery -A src.tasks worker -l info --without-gossip --without-mingle --without-heartbeat
    env_file:
      - .env.backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "170m"
        max-file: "5"
    restart: unless-stopped
    networks:
      - annuaire_staging_net

  celery-beat:
    image: ctrldaviddee/annuaire_did_be:staging-latest
    container_name: annuaire-celery-beat
    #command: celery -A src.tasks beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.backend
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "170m"
        max-file: "5"
    restart: unless-stopped
    networks:
      - annuaire_staging_net

volumes:
  postgres_data:
  rabbitmq_data:
  static_volume:
  media_volume:

networks:
  annuaire_staging_net:
    external: true