[project]
name = "did-annuaire-be1"
version = "0.1.0"
description = "DID Annuaire - Decentralized identifier application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    #"django-cors-headers>=4.9.0",
    #"django-filter>=25.2",
    #"django-storages>=1.14.6",
    #"whitenoise>=6.11.0",
    #"django-widget-tweaks>=1.5.1",
    "attrs>=25.4.0",
    "boto3>=1.42.25",
    "celery>=5.6.2",
    "dj-database-url>=3.1.0",
    "django>=6.0",
    "django-celery-beat>=2.8.1",
    "django-celery-results>=2.6.0",
    "django-debug-toolbar>=6.1.0",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "django-filter>=25.2",
    "django-ninja>=1.5.3",
    "django-ninja-extra>=0.30.8",
    "django-ninja-jwt[crypto]>=5.4.3",
    "django-structlog[celery]>=10.0.0",
    "gunicorn>=23.0.0",
    "hvac>=2.4.0",
    "psycopg[c]>=3.3.2",
    "pyld>=2.0.4",
    "pynacl>=1.6.2",
    "pyotp>=2.9.0",
    "qrcode[pil]>=8.2",
    "sentry-sdk[django]>=2.49.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar>=6.1.0",
    "rav>=0.2.0",
    "ruff>=0.14.11",
]


