[project]
name = "did-annuaire-be1"
version = "0.1.0"
description = "DID Annuaire - Decentralized identifier application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=25.4.0",
    "boto3>=1.42.17",
    "celery>=5.6.0",
    "django>=6.0",
    "django-celery-beat>=2.1.0",
    "django-celery-results>=2.6.0",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.12.0",
    "django-ninja>=1.5.1",
    "django-ninja-jwt[crypto]>=5.4.2",
    "django-storages>=1.14.6",
    "django-structlog[celery]>=10.0.0",
    "gunicorn>=23.0.0",
    "psycopg[c]>=3.3.2",
    "pyld>=2.0.4",
    "pyotp>=2.9.0",
    "sentry-sdk[django]>=2.48.0",
    "whitenoise>=6.11.0",
]


[dependency-groups]
dev = [
    "django-debug-toolbar>=6.1.0",
    "django-extensions>=4.1",
    "django-stubs>=5.2.8",
    "pre-commit>=4.5.1",
    "rav>=0.2.0",
    "ruff>=0.14.10",
]
