[project]
name = "did-annuaire-be1"
version = "0.1.0"
description = "DID Annuaire - Decentralized identifier application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.42.29",
    "celery>=5.6.2",
    "dj-database-url>=3.1.0",
    "django>=6.0.1",
    "django-celery-beat>=2.1.0",
    "django-celery-results>=2.6.0",
    "django-environ>=0.12.0",
    "django-extensions>=4.1",
    "django-ninja>=1.5.1",
    "django-ninja-jwt[crypto]>=5.4.3",
    "django-orbit>=0.5.0",
    "django-structlog[celery]>=10.0.0",
    "gunicorn>=23.0.0",
    "jsonschema>=4.26.0",
    "psycopg[c]>=3.3.2",
    "pyld>=2.0.4",
    "pyotp>=2.9.0",
    "qrcode[pil]>=8.2",
    "sentry-sdk[django]>=2.49.0",
]

[dependency-groups]
dev = [
    "django-debug-toolbar",
    "rav",
    "ruff",
]


